apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
  namespace: apps
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Hello Kubernetes !</title>
      <link rel="stylesheet" href="/css/main.css">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300">
      <style>
        body {
          font-family: 'Ubuntu', sans-serif;
          text-align: center;
          padding: 2rem;
        }
        .main {
          max-width: 600px;
          margin: 0 auto;
        }
        img {
          max-width: 200px;
        }
        table {
          margin: 1rem auto;
          border-collapse: collapse;
        }
        th, td {
          border: 1px solid #ccc;
          padding: 0.5rem 1rem;
          text-align: left;
        }
      </style>
    </head>
    <body>
      <div class="main">
        <img src="C:\Users\thnab\Pictures\KubernetesLogo.jpg" alt="Kubernetes Logo">
        <div class="content">
          <div id="message">
            Hello from app 1 !
          </div>
        </div>
      </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: app1-html
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: apps
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
