BOX = "generic/ubuntu2204"
MASTER_NAME = "nade-la-S"
WORKER_NAME = "nade-la-SW"
MASTER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.define MASTER_NAME do |master|
    master.vm.hostname = MASTER_NAME
    master.vm.network :private_network, ip: MASTER_IP

    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_NAME
    end

    master.vm.provision "shell",
      privileged: true,
      path: "scripts/master_setup.sh",
      args: [MASTER_IP]

    #master.vm.provision "shell",
      #privileged: true,
      #path: "scripts/deploy.sh"
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network :private_network, ip: WORKER_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
    end

    worker.vm.provision "shell",
      privileged: true,
      path: "scripts/worker_setup.sh",
      args: [MASTER_IP, WORKER_IP]
  end
end
