BOX = "generic/ubuntu2204"

MASTER_NAME = "nade-la-S"
WORKER_NAME = "nade-la-SW"
MASTER_IP = "192.168.42.110"
WORKER_IP = "192.168.42.111"

Vagrant.configure("2") do |config|
  
  config.vm.box = BOX
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.define MASTER_NAME do |master|
    master.vm.hostname = MASTER_NAME
    master.vm.network :private_network, ip: MASTER_IP

    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_NAME
    end


  # Provisioning : script de déploiement automatique après boot
  master.vm.provision "shell", privileged: true, path: "scripts/master_setup.sh", args: [MASTER_IP]
  
  # Provisionnement final : déploiement des ConfigMaps et applications
  master.vm.provision "shell", inline: <<-SHELL
    echo "Déploiement des ConfigMaps et applications"
    /usr/local/bin/kubectl create configmap app1-index --from-file=/vagrant/confs/app1/index.html --dry-run=client -o yaml | kubectl apply -f -
    /usr/local/bin/kubectl create configmap app2-index --from-file=/vagrant/confs/app2/index.html --dry-run=client -o yaml | kubectl apply -f -
    /usr/local/bin/kubectl create configmap app3-index --from-file=/vagrant/confs/app3/index.html --dry-run=client -o yaml | kubectl apply -f -
    /vagrant/scripts/deploy.sh
  SHELL
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network :private_network, ip: WORKER_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
    end

    worker.vm.provision "shell",
      privileged: true,
      path: "scripts/worker_setup.sh",
      args: [MASTER_IP, WORKER_IP]
  end
end